2024-01-18 12:38:27,380 INFO    MainThread:1551575 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-01-18 12:38:27,380 INFO    MainThread:1551575 [wandb_setup.py:_flush():76] Configure stats pid to 1551575
2024-01-18 12:38:27,381 INFO    MainThread:1551575 [wandb_setup.py:_flush():76] Loading settings from /home/ndhuynh/.config/wandb/settings
2024-01-18 12:38:27,381 INFO    MainThread:1551575 [wandb_setup.py:_flush():76] Loading settings from /home/ndhuynh/github/Question-Analysis/wandb/settings
2024-01-18 12:38:27,381 INFO    MainThread:1551575 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-18 12:38:27,381 INFO    MainThread:1551575 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-01-18 12:38:27,381 INFO    MainThread:1551575 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-18 12:38:27,381 INFO    MainThread:1551575 [wandb_init.py:_log_setup():526] Logging user logs to /home/ndhuynh/github/Question-Analysis/wandb/run-20240118_123827-hw090903/logs/debug.log
2024-01-18 12:38:27,381 INFO    MainThread:1551575 [wandb_init.py:_log_setup():527] Logging internal logs to /home/ndhuynh/github/Question-Analysis/wandb/run-20240118_123827-hw090903/logs/debug-internal.log
2024-01-18 12:38:27,382 INFO    MainThread:1551575 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7faaa4132af0>
2024-01-18 12:38:27,382 INFO    MainThread:1551575 [wandb_init.py:init():566] calling init triggers
2024-01-18 12:38:27,382 INFO    MainThread:1551575 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-01-18 12:38:27,382 INFO    MainThread:1551575 [wandb_init.py:init():616] starting backend
2024-01-18 12:38:27,382 INFO    MainThread:1551575 [wandb_init.py:init():620] setting up manager
2024-01-18 12:38:27,385 INFO    MainThread:1551575 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-01-18 12:38:27,428 INFO    MainThread:1551575 [wandb_init.py:init():628] backend started and connected
2024-01-18 12:38:27,436 INFO    MainThread:1551575 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-01-18 12:38:27,437 INFO    MainThread:1551575 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-01-18 12:38:27,437 INFO    MainThread:1551575 [wandb_init.py:init():720] updated telemetry
2024-01-18 12:38:27,508 INFO    MainThread:1551575 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-01-18 12:38:27,841 ERROR   MainThread:1551575 [wandb_init.py:init():779] encountered error: You provided an invalid value for the `resume` argument. The value 'must' is not a valid option for resuming a run (hw090903) that does not exist. Please check your inputs and try again with a valid run ID. If you are trying to start a new run, please omit the `resume` argument or use `resume='allow'`.
2024-01-18 12:38:28,217 ERROR   MainThread:1551575 [wandb_init.py:init():1194] You provided an invalid value for the `resume` argument. The value 'must' is not a valid option for resuming a run (hw090903) that does not exist. Please check your inputs and try again with a valid run ID. If you are trying to start a new run, please omit the `resume` argument or use `resume='allow'`.
Traceback (most recent call last):
  File "/home/ndhuynh/.conda/envs/hie/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home/ndhuynh/.conda/envs/hie/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.UsageError: You provided an invalid value for the `resume` argument. The value 'must' is not a valid option for resuming a run (hw090903) that does not exist. Please check your inputs and try again with a valid run ID. If you are trying to start a new run, please omit the `resume` argument or use `resume='allow'`.
2024-01-18 12:38:48,473 INFO    MainThread:1551575 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-01-18 12:38:48,473 INFO    MainThread:1551575 [wandb_setup.py:_flush():76] Configure stats pid to 1551575
2024-01-18 12:38:48,473 INFO    MainThread:1551575 [wandb_setup.py:_flush():76] Loading settings from /home/ndhuynh/.config/wandb/settings
2024-01-18 12:38:48,473 INFO    MainThread:1551575 [wandb_setup.py:_flush():76] Loading settings from /home/ndhuynh/github/Question-Analysis/wandb/settings
2024-01-18 12:38:48,473 INFO    MainThread:1551575 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-18 12:38:48,473 INFO    MainThread:1551575 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-01-18 12:38:48,474 INFO    MainThread:1551575 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-18 12:38:48,474 INFO    MainThread:1551575 [wandb_init.py:_log_setup():526] Logging user logs to /home/ndhuynh/github/Question-Analysis/wandb/run-20240118_123848-hw090903/logs/debug.log
2024-01-18 12:38:48,474 INFO    MainThread:1551575 [wandb_init.py:_log_setup():527] Logging internal logs to /home/ndhuynh/github/Question-Analysis/wandb/run-20240118_123848-hw090903/logs/debug-internal.log
2024-01-18 12:38:48,474 INFO    MainThread:1551575 [wandb_init.py:init():566] calling init triggers
2024-01-18 12:38:48,475 INFO    MainThread:1551575 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-01-18 12:38:48,475 INFO    MainThread:1551575 [wandb_init.py:init():616] starting backend
2024-01-18 12:38:48,475 INFO    MainThread:1551575 [wandb_init.py:init():620] setting up manager
2024-01-18 12:38:48,478 INFO    MainThread:1551575 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-01-18 12:38:48,478 INFO    MainThread:1551575 [wandb_init.py:init():628] backend started and connected
2024-01-18 12:38:48,481 INFO    MainThread:1551575 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-01-18 12:38:48,481 INFO    MainThread:1551575 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-01-18 12:38:48,481 INFO    MainThread:1551575 [wandb_init.py:init():720] updated telemetry
2024-01-18 12:38:48,498 INFO    MainThread:1551575 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-01-18 12:40:18,520 ERROR   MainThread:1551575 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-01-18 12:40:18,551 ERROR   MainThread:1551575 [wandb_init.py:init():1194] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/home/ndhuynh/.conda/envs/hie/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home/ndhuynh/.conda/envs/hie/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
